### PR TITLE
feat: Add page for david blackwelder

### PR DESCRIPTION
**Pull request by davidblackwelder**
- Add a card for me to the home page.
- Add a page for me that displays the weather

### CODE REVIEW

**Review by cgm42 — APPROVED** [review]

**Review by davidleegriffin — APPROVED** [review]

**Comment by davidleegriffin** [comment]
hey can you do a <npm run lint> and a <npm run format> on your machine so it will pass the linter test on github and I can approve?
thx,Dave





    On Tuesday, September 7, 2021, 02:00:07 AM CDT, David Blackwelder ***@***.***> wrote:  
 
 


@davidblackwelder requested your review on: #8 feat: Add page for david blackwelder.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cgm42** [comment]
> hey can you do a <npm run lint> and a <npm run format> on your machine so it will pass the linter test on github and I can approve? thx,Dave On Tuesday, September 7, 2021, 02:00:07 AM CDT, David Blackwelder ***@***.***> wrote: @davidblackwelder requested your review on: #8 feat: Add page for david blackwelder. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Have you tried npm run format?

**Comment by davidleegriffin** [comment]
yeah, but i had to remove node_modules and package-lock.json and npm i then format and lint and that did the trick should be good to go.
Dave
    On Tuesday, September 7, 2021, 05:15:50 PM CDT, Carrie G ***@***.***> wrote:  
 
 



hey can you do a  and a on your machine so it will pass the linter test on github and I can approve? thx,Dave On Tuesday, September 7, 2021, 02:00:07 AM CDT, David Blackwelder @.***> wrote: @davidblackwelder requested your review on: #8 feat: Add page for david blackwelder. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


Have you tried npm run format?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by davidblackwelder** [comment]
Thanks David, I will try removing my node_modules and package-lock. Reinstalling npm packages and then running the checks. 

I am out right now but will do this tonight when I'm back home.

**Pull request merged**
